server:
  port: 8002
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/xy_dash?serverTimezone=GMT%2B8&useSSL=FALSE&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wxwmys999
      # druid 全局配置
    druid:
     initialSize: 10
     minIdle: 5
     maxActive: 50
     # 配置获取连接等待超时的时间
     maxWait: 60000
     # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
     timeBetweenEvictionRunsMillis: 60000
     # 配置一个连接在池中最小生存的时间，单位是毫秒
     minEvictableIdleTimeMillis: 300000
     #        validationQuery: SELECT 1 FROM DUAL
     #        testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     # 打开PSCache，并且指定每个连接上PSCache的大小
  mvc:
    async:
      request-timeout: 30000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#logging:
#  level:
#    com.xy.dash.mapper: debug


swagger:
  enable: true